FROM default-route-openshift-image-registry.apps.ocp4.example.com/test-cp4i/ace-server-prod-11:11.0.0.13-r1-eus
COPY Customer /home/aceuser/Customer
RUN export LICENSE="accept" \
    && source /opt/ibm/ace-11/server/bin/mqsiprofile \
    && mkdir /home/aceuser/bars \
    && mqsipackagebar -a bars/FE.bar -k Customer \
    && mqsibar -a bars/FE.bar -w /home/aceuser/ace-server \
    && chmod -R 777 /home/aceuser/ace-server/run/Customer
